// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANaTtQcwN2ronL0sEbluZ3kdUBqumP0QI',
    appId: '1:374425801476:web:1398e16fcc402110afb651',
    messagingSenderId: '374425801476',
    projectId: 'echo-news-126fa',
    authDomain: 'echo-news-126fa.firebaseapp.com',
    storageBucket: 'echo-news-126fa.firebasestorage.app',
    measurementId: 'G-418ZW34VXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HSKOPnLzIAg08i9sd7HRxI523NxwXZI',
    appId: '1:374425801476:android:e56ad7497ffa18a4afb651',
    messagingSenderId: '374425801476',
    projectId: 'echo-news-126fa',
    storageBucket: 'echo-news-126fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVyB4QUUX9qiZvSWOPaXDyLHDppyG8Szo',
    appId: '1:374425801476:ios:e576e3a806f8c515afb651',
    messagingSenderId: '374425801476',
    projectId: 'echo-news-126fa',
    storageBucket: 'echo-news-126fa.firebasestorage.app',
    iosBundleId: 'com.example.echoNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVyB4QUUX9qiZvSWOPaXDyLHDppyG8Szo',
    appId: '1:374425801476:ios:e576e3a806f8c515afb651',
    messagingSenderId: '374425801476',
    projectId: 'echo-news-126fa',
    storageBucket: 'echo-news-126fa.firebasestorage.app',
    iosBundleId: 'com.example.echoNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANaTtQcwN2ronL0sEbluZ3kdUBqumP0QI',
    appId: '1:374425801476:web:d5eb9156d090c8a1afb651',
    messagingSenderId: '374425801476',
    projectId: 'echo-news-126fa',
    authDomain: 'echo-news-126fa.firebaseapp.com',
    storageBucket: 'echo-news-126fa.firebasestorage.app',
    measurementId: 'G-P39EPFH211',
  );

}